### ISSUE TITLE
The alignment of the location of server entry in Peer connection section is not properly aligned

### ISSUE THREAD

**Issue by selavazhagan** [GoogleChrome/webrtc#149]
1. Login to the http://kaptenjansson.github.io/webrtc/samples/web/content/manual-test/peer2peer/
2. Under Peer Connection section enter the Server info into the box next to the 'Signal server[?]:' and click on Connect next to the 'Peer ID'

Expected Result:
The alignment should not change

Actual Result:
The alignment changes as seen in the screen shot.  This happens only when the details are entered and clicked on 'Connect'

![screenshot 2014-10-13 at 10 11 31 am](https://cloud.githubusercontent.com/assets/9001606/4617234/4feebc0c-52fc-11e4-98b9-9b79b265ffc3.png)

**Comment by KaptenJansson** [comment]
This is fixed for some cases but not all. Filed new issue in the repo.
