### ISSUE TITLE
Add camera selection

### ISSUE THREAD

**Issue by samdutton** [GoogleChrome/webrtc#222]
Add functionality for camera selection by tapping/clicking an icon in the toolbar.

To see a version of this in action, ensure you have two cameras connected to your device, then open two clients from [apprtc-m.appspot.com](apprtc-m.appspot.com) and hover over the video. Click on the camera icon to swap cameras.

**Comment by jiayliu** [comment]
Dup of https://github.com/webrtc/apprtc/issues/8
