### ISSUE TITLE
Add README or wiki page to document AppRTC URL params

### ISSUE THREAD

**Issue by juberti** [GoogleChrome/webrtc#315]
Basically, an official version of http://gingertech.net/2014/03/19/apprtc-googles-webrtc-test-app-and-its-parameters/

**Comment by KaptenJansson** [comment]
Currently the Apprtc params [link](https://apprtc.appspot.com/params.html) on [index.html](https://github.com/GoogleChrome/webrtc/blob/master/index.html) and [README.md[(https://github.com/GoogleChrome/webrtc/blob/master/README.md) gives a 404.

**Comment by samdutton** [comment]
@marwahvikas [params.html](https://apprtc.appspot.com/params.html) will need to be deployed as a static file on apprtc.appspot.com.

I've fixed the other two broken links (interop and testing parameters) in my most recent commit.

**Comment by juberti** [comment]
https://github.com/GoogleChrome/webrtc/pull/362 moves params.html to the /html subdir, which is already publicly served. But perhaps we should just update app.yaml to route requests for help.html and params.html to the /html subdir (and move all the html files there)

**Comment by jiayliu** [comment]
Should this be closed?

**Comment by juberti** [comment]
File new issue based on my prior comment, then you can close

**Comment by jiayliu** [comment]
Moved to https://github.com/webrtc/apprtc/issues/22
