### ISSUE TITLE
Test to capture/detect "WiFi Scanning" problems

### ISSUE THREAD

**Issue by andresusanopinto** [GoogleChrome/webrtc#324]
It is clear to me now, there is a need for a test that can be run from a browser that identifies if there is periodic network glitches or similar issues which are caused by a likely bad wifi drivers that add a big latency (>2seconds at a times) to keep its list of networks and APs up to date.

Luckily I am now the owner of a laptop with the issue!

**Comment by KaptenJansson** [comment]
This is fixed in #426 and #329 among others.
