### ISSUE TITLE
TestRTC to show useful message when WebRTC is not supported

### ISSUE THREAD

**Issue by jiayliu** [GoogleChrome/webrtc#342]
Try loading test-rtc.appspot.com on Chrome for iOS.

Result: blank page.

**Comment by KaptenJansson** [comment]
I believe this is due to WebRTC is not part of Safari/webkit from iOS which browsers on iOS have to use. Also, only Safari have access to the accelerated javascript engine.

We could however add an error message, the page should clearly not go blank.

**Comment by KaptenJansson** [comment]
Actually, the reason it's blank is most likely issue #344. However WebRTC will not work nonetheless.

**Comment by andresusanopinto** [comment]
@KaptenJansson do you want to add another paper-dialog to show when basic functionality is not supported?

**Comment by KaptenJansson** [comment]
Yeah sure, I need to figure out why Safari, IE and Chrome on iOS cannot read the global variable values of another JS file before (#344).
