### ISSUE TITLE
TestRTC: error message could be more informative

### ISSUE THREAD

**Issue by jiayliu** [GoogleChrome/webrtc#343]
Open test-rtc.appspot.com on Chrome on Android, tap Start.

Result:
Failures are reported under "Camera" with messages:
[FAILED] Incorrect captured width
[FAILED] Incorrect captured height

Expected:
The error message could be more useful if it includes what is the expected value and what is the actual value.

**Comment by KaptenJansson** [comment]
I believe this is planned for v2.0, i.e. make all user facing messages make sense to the user.

**Comment by andresusanopinto** [comment]
TestRTC purpose is to help debugging issues where one needs more data on how the system behaves. As so the main output is its report (Can you confirm the expected and actual resolution are there?).

Honestly i don't think telling the user the width was different expected 360 got 480, would provide benefit over saying the camera did not provide the resolution it was asked for. If not it would only make most users confused by reading information they do not know how to act on.

**Comment by andresusanopinto** [comment]
Confirmed the report has all the information needed to debug the issue (see #271)
