### ISSUE TITLE
TestRTC - Internet Explorer and Safari issues with polymer and AudioContext

### ISSUE THREAD

**Issue by KaptenJansson** [GoogleChrome/webrtc#344]
It executes functions in the test case javascript files before the global variables in main.js are defined (Error SCRIPT5007 when addTest() in mictest.js (i.e. first testcase file) when trying to access length method on the global variable testSuites in main.js).

Found this while looking at providing some error message on non WebRTC browsers like internet explorer 10, safari, Chrome on iOS etc. Issue #342 brought this to my attention.

Either we fix this now by adding IE exception handling or when IE supports WebRTC alongside the fix (check if browser is WebRTC compatible else show error message to user instead of a blank page) for #342.

**Comment by KaptenJansson** [comment]
It happens in safari too. Seems like the variable is declared in the global scope however it's never assigned.

**Comment by KaptenJansson** [comment]
Also FYI safari and ie does not recognize AudioContext (safari uses prefix webkit while ie 11 does not support WebAudio yet)

**Comment by KaptenJansson** [comment]
So it seems other JS files (mictest.js etc) cannot access the values of global variables in main.js.

**Comment by samdutton** [comment]
Regarding AudioContext, we should use this shim: 

    window.AudioContext = window.AudioContext || window.webkitAudioContext;

**Comment by andresusanopinto** [comment]
I find this thread a bit confusing... I would guess there is some JS error in the main.js that makes so that the rest of the file is not executed and the symbols never defined (instead of something such as not recognizing global variables).

Can you provide a report from those browsers? The JS errors should be in it.

**Comment by KaptenJansson** [comment]
Yeah sure.

**Comment by KaptenJansson** [comment]
Conclusion of yesterday's investigation:

* reportError on line 355 in main.js is called due to the browser not supporting MediaStreamTrack, this is throws en exception because report error has methods that rely on that the Test constructor has been created (currentTest.reportError etc)
* AudioContext is not supported on IE while Safari uses the webkit prefix.
* Polymer is not loaded for some reason (even after fixing the above errors) on IE and Safari. Polymer uses a shim (which is now part of webcomponents.js which we use) for unsupported functionality in the browser and according to the Polymer compatibility chart latest IE and Safari should be supported.

Solution:
Fix reportError and AudioContext errors by adding a robust general error handling mechanism and shim WebAudio as suggested by samdutton. 

This should include a dependency check for all the required components like WebRTC components, WebAudio and Polymer. If any of these fails present the user with an error.

The question is if we should add a two different error popups for if polymer is loaded or not or just do one that is not dependent on polymer?
