### ISSUE TITLE
Grunt fails due to appengine sdk update

### ISSUE THREAD

**Issue by jiayliu** [GoogleChrome/webrtc#371]
Running "shell:runPythonTests" (shell) task
[google_appengine_1.9.15.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of google_appengine_1.9.15.zip or
        google_appengine_1.9.15.zip.zip, and cannot find google_appengine_1.9.15.zip.ZIP, period.
Warning: Command failed: [google_appengine_1.9.15.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of google_appengine_1.9.15.zip or
        google_appengine_1.9.15.zip.zip, and cannot find google_appengine_1.9.15.zip.ZIP, period.
 Use --force to continue.

Aborted due to warnings.

https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.15.zip returns:

<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
</Error>

The https://cloud.google.com/appengine/downloads page says 1.9.17 is the new version.

**Comment by chuckhays** [comment]
I hit the same thing and had to hard code "1.9.17" as the version in the run_python_tests.sh file to get it to complete. A quick search on the web suggests this same thing happened a couple months back with the prior version as well.

**Comment by phoglund** [comment]
Really. Hm, I wrote it to figure this out by itself but it appears that did not work. I'll take a look.

**Comment by phoglund** [comment]
I made a pull request now which works around this. Feel free to merge if you're happy with it.
