### ISSUE TITLE
60FPS and 1080 buttons for apprtc

### ISSUE THREAD

**Issue by KaptenJansson** [GoogleChrome/webrtc#372]
I propose adding a couple of buttons for apprtc:
* 1080 mode (minWidth=1920, minHeight=1080)
* 60 FPS HD mode (maxFramRate=60, minWidth=1280, minHeight=720)

Yes, these can be activated via URL params but not sure how many do that and it would expose those features even more.

Also activating these requires a page reload or stopping current stream and request a new gum stream and attach it to the peerconnection. I vote for the latter.

If we want to save the selections we could use localStorage.

Note: To actually get 1080 and/or 60FPS will most likely require a capture device with a 1080 60fps capable camera connected to it hence the audience will be small but I think it's a small effort nonetheless to showcase smooth video using WebRTC!

**Comment by KaptenJansson** [comment]
FYI it seems that 1080 actually only gives around 10fps atm in M41.

So maybe just add 60fps@720 for now as that seems to work fine.

**Comment by KaptenJansson** [comment]
NVM if the machine and camera is capable of 60fps it actually deliver it....

**Comment by samdutton** [comment]
That was easy ;).

**Comment by KaptenJansson** [comment]
Really fast implementation! ;)

**Comment by samdutton** [comment]
Thank you ;).
