### ISSUE TITLE
No Speaker Detection Support

### ISSUE THREAD

**Issue by KrishPS** [GoogleChrome/webrtc#384]
Hi,

I have tried many methods of JavaScript to detect local speakers & checked your given example as well. But nothing is working.

Could you please me to use correct API to detect local speakers?
Thanks in Advance

Thanks,
KrishPS

**Comment by KaptenJansson** [comment]
It's not finalized in the standard yet, details in this [bug](https://code.google.com/p/chromium/issues/detail?id=438023). TL;DR proposal [here](http://w3c.github.io/mediacapture-output/)

**Comment by KrishPS** [comment]
Thanks a lot for the info.
