### ISSUE TITLE
AppRTC - Sometimes video is not setup correctly

### ISSUE THREAD

**Issue by KaptenJansson** [GoogleChrome/webrtc#399]
Steps to reproduce:
1. User 1 - Browse to https://apprtc.appspot.com 
2. User 2 - Copy the URL to another machine
3. Verify that Audio and Video is flowing.

Actual Result:
Only audio is flowing and only one side has the hangup button (machine in step 2).
I've seen this using multiple Chrome version (M39, M40, M41 and M42) and on different machines hence I do not think it's the client's fault.

Webrtc-internals:
User 1: https://drive.google.com/a/google.com/file/d/0BwwlrcPnEG-RWG9TMVNJaGFwbUk/view?usp=sharing
User 2: https://drive.google.com/a/google.com/file/d/0BwwlrcPnEG-ROFhMTmk0ZVR6ZnM/view?usp=sharing

Console dump:
User 1: https://docs.google.com/a/google.com/document/d/1EHJBYxU8X0JowDDLYO7RCmPPaGtQR7qzRzDIodPVZ5c/edit?usp=sharing
User 2: https://docs.google.com/a/google.com/document/d/1peNlLdSbvX-whIQlobGc7tP9x2dusyY-BKHH4igwFYc/edit?usp=sharing

Sam, not sure if you are the right person to debug this, if not, please reassign.

**Comment by juberti** [comment]
@jiayl @tkchin this seems like a signaling problem, let's figure out what's going on here.

**Comment by rschriebman** [comment]
This is pretty easy for me to repro, been 100% with these steps:
1. Connect with two accounts (one Linux, one Windows, if it matters)
2. Refresh one page.
3. Observe that only one client believes there are two streams in the room (the non refreshed page)

Repeating this process has the non refreshed page go through a fun little cycle:
1. Two people in room.
2. Alone in room.
3. Giant black screen.
4. Two people in room
etc.
Sometimes the filmstrip is black for the self vidoe when the client thinks there are two people (the refreshed client still sees video properly).

**Comment by jiayliu** [comment]
The log shows the input frame rate of user2 is 0:
"ssrc_2630867406_send-googFrameRateInput": {
     "startTime": "2015-01-19T14:44:54.173Z",
     "endTime": "2015-01-19T14:44:57.637Z",
     "values": "[0,0,0,0,0,0,0,0]"
    },
    "ssrc_2630867406_send-googFrameRateSent": {
     "startTime": "2015-01-19T14:44:54.173Z",
     "endTime": "2015-01-19T14:44:57.637Z",
     "values": "[0,0,0,0,0,0,0,0]"
    },
User1 does not see hangup button is expected since no remote video has arrived.
So it looks like a problem with getUserMedia on user 2.
I'll try to reproduce.

**Comment by juberti** [comment]
This is an interesting privacy consideration, i.e. we need to still transition to the in-call state somehow if we are sending video but not receiving it. Perhaps we need some sort of timer.

**Comment by jiayliu** [comment]
I cannot repro Jansson's issue, but I found a race condition which may cause the issues rschriebman reported. Sent a PR https://github.com/GoogleChrome/webrtc/pull/420 for that.

Agree to Justin that we should transition the UI in case of no remote video data coming. Why don't we transition to active as soon as the ICE connection state changes to connected?

**Comment by juberti** [comment]
I don't think we should transition to blackness (i.e. if it takes a second for media to arrive, don't transition until media is ready). However we shouldn't wait forever - 3 seconds might be a good max.

**Comment by jiayliu** [comment]
The issue rschriebman reported has been fixed.

@KaptenJansson, 

What's the OS of user 2? How often does it happen? Can you get chrome and webrtc logging?

**Comment by KaptenJansson** [comment]
I believe it was between Linux and Windows but I can no longer reproduce. I think we can close this issue for now.
