### ISSUE TITLE
The local preview video is not seen in the successful two way apprtc call 

### ISSUE THREAD

**Issue by selavazhagan** [GoogleChrome/webrtc#409]
1. Successfully join the two way apprtc call between Pit and Daisy, both with the same builds(41.02272.6/6680.4.0)
2. Check for the video preview locally for the user in the device Pit
![screenshot 2015-01-21 at 1 47 00 pm](https://cloud.githubusercontent.com/assets/9001606/5846122/2949e05e-a176-11e4-9065-9566b094bcec.png)

Expected result: The video should be seen both locally and remotely.  

Actual Result: the video is not seen locally, but seen remotely.  Checked the Webrtc-internals and seeing the sent and received video and audio stats and graphs are seen ok.

**Comment by juberti** [comment]
I think this should be filed in the Chromium tracker, as it's not an application bug.
