### ISSUE TITLE
Materialize landing page buttons and input field

### ISSUE THREAD

**Issue by juberti** [GoogleChrome/webrtc#410]
The current landing page works great, but the UI looks a bit... Microsofty.

![screen shot 2015-01-21 at 7 02 59 pm](https://cloud.githubusercontent.com/assets/1821693/5849851/28ac40b8-a1a0-11e4-8c3d-ba5b69e75381.png)

The buttons and input field should follow the style from
https://www.polymer-project.org/docs/elements/paper-elements.html#paper-button
https://www.polymer-project.org/docs/elements/paper-elements.html#paper-input

**Comment by chuckhays** [comment]
Agreed, I just took the rough style Sam suggested from: http://googlechrome.github.io/webrtc/samples/web/content/getusermedia/resolution/

Should we pull in the polymer framework and use that for the web UI going forward?

**Comment by samdutton** [comment]
>
> Should we pull in the polymer framework and use that for the web UI going
> forward?


Yes. I think this would make a lot of sense.

(For apprtc, I wanted to keep the page weight and number of requests to a
minimum, so I used inline SVGs in a 'material' style.)


---------- Forwarded message ----------

**Comment by juberti** [comment]
I think that would probably be simplest, although let's check how much this actually adds in terms of requests/bytes first. We have such a small number of UI elements, it would be nice to avoid paying for stuff we aren't using.

**Comment by chuckhays** [comment]
Here is the same UI using polymer. It isn't ready for a PR yet. If we decide to move forward I need to update some tests and make sure it works in the Chrome App. 

Uses the blue colors from the material design spec, and has the default animations included with polymer.

I'll check how many files/sizes that it fetches and report back.

https://github.com/chuckhays/webrtc/commit/a815d2ac531d353977d98041080fc3038eb9264b

![screen shot 2015-01-22 at 4 08 10 pm](https://cloud.githubusercontent.com/assets/1405600/5867427/eedd3ff2-a250-11e4-832e-d8c30b2584e7.png)
![screen shot 2015-01-22 at 4 08 24 pm](https://cloud.githubusercontent.com/assets/1405600/5867428/f0cfba74-a250-11e4-99d7-298ac7e5b0f7.png)

**Comment by chuckhays** [comment]
Here is a list of the files additionally fetched with this change:




| File                         | Size (KB)|
|------------------------------|-----|
| paper-button.html             |5.3  |
| paper-input.html              |3.9  |
| paper-item.html               |3.8  |
|paper-shadow.html             |2.5  |
|polymer.html                  |0.798|
|core-ally-keys.html           |10.7|
|paper-button-base.html        |4.3|
|core-input.html               |3.7|
|paper-input-decorator.html    |16.4|
|paper-ripple.html|14.3|
|paper-shadow.css|2|
|layout.html|6|
|polymer.js|336|
|core-focusable.html|0.353|
|core-icon.html|6.1|
|core-icons.html|54.4|
|core-style.html|10.9|
|polymer-mixin.js|1.1|
|core-focusable.js|3.2|
|core-iconset-svg.html|5.4|
|core-iconset.html|8.4|
|core-icon.css|0.898|
|core-meta.html|4|
|paper-input-decorator.css|2.7|
|**Total**|**507.149(KB)**|

**Comment by juberti** [comment]
It certainly looks great. Is there a minified version?

500K is a lot to take on, but I don't want to spend a ton of time trying to recreate Polymer. And this stuff is all cacheable.

**Comment by chuckhays** [comment]
It does look like they also have a tool called vulcanize which can combine a lot of it into a single page. It would make index.html bigger, but take only 1 network request.

Polymer seems bleeding edge enough that we should consider whether it supports all the browsers we want to work with AppRTC or not.

**Comment by juberti** [comment]
That might work against caching, since index.html won't be cached. But I like the idea of a single blob, possibly downloadable as a polymer.html fragment. Were the numbers above from minified versions of Polymer?

If we're not sure what direction we want to go, we could just manually specify the colors/basic stylings from Material (uppercase buttons, etc) as a first step.

**Comment by chuckhays** [comment]
Here is a CSS/HTML only option that gets much closer to the guidelines:

https://github.com/chuckhays/webrtc/commit/5e9d8b8b870097c58067b7f3e99fd2beb9d00120

![screen shot 2015-01-23 at 11 12 12 am](https://cloud.githubusercontent.com/assets/1405600/5880883/cdfa543c-a2f0-11e4-85fe-7d7ad9c980f0.png)
![screen shot 2015-01-23 at 11 12 27 am](https://cloud.githubusercontent.com/assets/1405600/5880884/cdfc0318-a2f0-11e4-8675-6218220f4b2e.png)
![screen shot 2015-01-23 at 11 14 41 am](https://cloud.githubusercontent.com/assets/1405600/5880930/0e509b72-a2f1-11e4-8424-0a1fdd4b7579.png)

**Comment by juberti** [comment]
Perfect. Let's go with that.
