### ISSUE TITLE
AppRTC needs greenroom when going to /r/XXXX

### ISSUE THREAD

**Issue by juberti** [GoogleChrome/webrtc#421]
To protect against embeddings transmitting video without consent, there needs to be an extra "Join" step when joining a room via /r/. We don't need this on the caller side since we have the landing page, and we won't need this on incoming calls, but direct join via /r/ needs this.

**Comment by jiayliu** [comment]
The caller can join a room via /r/ as well and the malicious site can join
as the callee steal information.
It seems we need to ask the user to confirm for all /r/ for both caller and
callee.

On Fri, Jan 23, 2015 at 11:49 AM, Justin Uberti <notifications@github.com>
wrote:

> Assigned #421 <https://github.com/GoogleChrome/webrtc/issues/421> to
> @jiayliu <https://github.com/jiayliu>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleChrome/webrtc/issues/421#event-223923841>.
>



-- 
Jiayang Liu

**Comment by juberti** [comment]
Agreed, I just meant that with the landing page, the caller typically won't go through /r/.

**Comment by jiayliu** [comment]
Another thought: why do we even support /r/ now we have the landing page?

On Fri, Jan 23, 2015 at 2:42 PM, Justin Uberti <notifications@github.com>
wrote:

> Agreed, I just meant that with the landing page, the caller typically
> won't go through /r/.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleChrome/webrtc/issues/421#issuecomment-71279098>.
>



-- 
Jiayang Liu

**Comment by juberti** [comment]
Direct links in calendar, or sharing on social media, etc

**Comment by jiayliu** [comment]
I think we can redirect them to the landing page with the room input box
populated with the room from the url.

On Fri, Jan 23, 2015 at 3:01 PM, Justin Uberti <notifications@github.com>
wrote:

> Direct links in calendar, or sharing on social media, etc
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleChrome/webrtc/issues/421#issuecomment-71281460>.
>



-- 
Jiayang Liu

**Comment by jiayliu** [comment]
I didn't mean a real HTTP redirect, but just use the same landing page UI.

On Fri, Jan 23, 2015 at 3:04 PM, Jiayang Liu <jiayl@google.com> wrote:

> I think we can redirect them to the landing page with the room input box
> populated with the room from the url.
>
> On Fri, Jan 23, 2015 at 3:01 PM, Justin Uberti <notifications@github.com>
> wrote:
>
>> Direct links in calendar, or sharing on social media, etc
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/GoogleChrome/webrtc/issues/421#issuecomment-71281460>
>> .
>>
>
>
>
> --
> Jiayang Liu
>



-- 
Jiayang Liu

**Comment by juberti** [comment]
I don't think we want the exact same UI (why give the option to change the room id?), but having the selfview show along with the Join button from the existing UI should work well.

**Comment by samdutton** [comment]
Also, do we want something like this:

this.top.location !== this.location && (this.top.location = this.location);


(See css-tricks.com/snippets/javascript/break-out-of-iframe - window can be
overridden.)

**Comment by juberti** [comment]
That might be a good thing, in order to discourage embedders, but it's separate from the core issue here.
