### ISSUE TITLE
Visible version info in apprtc

### ISSUE THREAD

**Issue by tednakamura** [GoogleChrome/webrtc#449]
As far as I can tell, there isn't an easy way to determine what version of apprtc is running. Would it be possible to add some sort of version identifier, such as the git hash of where the binary was last cut, somewhere in the UI? Since that version id wouldn't need to be visible all the time, perhaps it could be included in the debug pane that appears when pressing "i"?

@jiayliu and @marwahvikas - what do you think?

**Comment by marwahvikas** [comment]
sounds good to me Ted, Jiayang what are your thoughts?

**Comment by jiayliu** [comment]
Are you talking about the client version or server version?

We currently maintain the server version in the deployment spreadsheet.

If we want to show it in the UI, we need to add a field to the GAE
manifest, and pass it to the clients.
And we need to maintain the field manually.

On Thu, Jan 29, 2015 at 2:47 PM, Ted Nakamura <notifications@github.com>
wrote:

> As far as I can tell, there isn't an easy way to determine what version of
> apprtc is running. Would it be possible to add some sort of version
> identifier, such as the git hash of where the binary was last cut,
> somewhere in the UI? Since that version id wouldn't need to be visible all
> the time, perhaps it could be included in the debug pane that appears when
> pressing "i"?
>
> @jiayliu <https://github.com/jiayliu> and @marwahvikas
> <https://github.com/marwahvikas> - what do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleChrome/webrtc/issues/449>.
>



-- 
Jiayang Liu

**Comment by tednakamura** [comment]
> Are you talking about the client version or server version?
Server

> We currently maintain the server version in the deployment spreadsheet.
Is that spreadsheet publicly visible? Even if it is, I think it still might be easier to tell people, when filing bugs against the apprtc server instance, to just look in the UI and include that version ID in the bug report. 

> And we need to maintain the field manually.
...but if there isn't an automated way to handle this, perhaps it's not worth the effort? If you agree, feel free to close this issue. I can always revisit this idea if the need arises.

**Comment by jiayliu** [comment]
We probably can write a deploy script which updates the manifest
automatically. It will be useful for the analytics change Donald is working
on which also requires configuring a file not in the repo.

I'll take a look into it.

On Fri, Jan 30, 2015 at 10:49 AM, Ted Nakamura <notifications@github.com>
wrote:

> Are you talking about the client version or server version?
> Server
>
> We currently maintain the server version in the deployment spreadsheet.
> Is that spreadsheet publicly visible? Even if it is, I think it still
> might be easier to tell people, when filing bugs against the apprtc server
> instance, to just look in the UI and include that version ID in the bug
> report.
>
> And we need to maintain the field manually.
> ...but if there isn't an automated way to handle this, perhaps it's not
> worth the effort? If you agree, feel free to close this issue. I can always
> revisit this idea if the need arises.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleChrome/webrtc/issues/449#issuecomment-72249989>.
>



-- 
Jiayang Liu

**Comment by juberti** [comment]
Just having the build date stamped into the infobox somehow would be a great first step.
What's the thinking around putting this into the manifest?

**Comment by jiayliu** [comment]
I can we can create a deploy script that update the manifest automatically.

**Comment by jiayliu** [comment]
Maybe not adding the version the manifest, but a separate json file.

On Fri, Jan 30, 2015 at 5:16 PM, Jiayang Liu <jiayl@google.com> wrote:

> I can we can create a deploy script that update the manifest automatically.
> On Jan 30, 2015 5:11 PM, "Justin Uberti" <notifications@github.com> wrote:
>
>> Just having the build date stamped into the infobox somehow would be a
>> great first step.
>> What's the thinking around putting this into the manifest?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/GoogleChrome/webrtc/issues/449#issuecomment-72296939>
>> .
>>
>


-- 
Jiayang Liu

**Comment by jiayliu** [comment]
fixed
